### PR TITLE
Add --json flag

### LINKED ISSUE #4: Add `--json` command line flag
Currently we have the following output

```
examples/syntax-error.nix:7 (7,5)-(7,15)
examples/semantic.nix:6 (6,5)-(6,15)
```

For composition with other tools, it would be good to have a CLI flag to output JSON instead.

### PR DESCRIPTION
**Pull request by siraben**
Closes #4

### CODE REVIEW

**Comment by siraben** [comment]
cc @ckiee, how do I regenerate the `yarn.nix` file?

**Comment by ckiee** [comment]
`nix-shell -p yarn2nix --run 'yarn2nix > yarn.nix'`

**Comment by Artturin** [comment]
I think it'd be good to use json internally always and then transform it in to user readable output and keep it as json if --json is used

**Comment by Artturin** [comment]
for reference this is what pylint outputs when `-f json` is used

```json
[
    {
        "type": "convention",
        "module": "organize_home.main",
        "obj": "move_not_my_repos",
        "line": 11,
        "column": 0,
        "endLine": 32,
        "endColumn": 73,
        "path": "src/organize_home/main.py",
        "symbol": "missing-function-docstring",
        "message": "Missing function or method docstring",
        "message-id": "C0116"
    },
    {
        "type": "convention",
        "module": "organize_home.main",
        "obj": "",
        "line": 7,
        "column": 0,
        "endLine": 7,
        "endColumn": 24,
        "path": "src/organize_home/main.py",
        "symbol": "wrong-import-order",
        "message": "standard import \"from pathlib import Path\" should be placed before \"import magic\"",
        "message-id": "C0411"
    }
]

```

**Comment by siraben** [comment]
One issue is that I might not be able to print the JSON until the very end, so the UX might be a bit degraded.

**Comment by siraben** [comment]
@ckiee it appears so

**Comment by Artturin** [comment]
git rebase `origin/master` should add the commits without showing them here

**Pull request merged**
